AllCops:
  TargetRubyVersion: 3.0

  Exclude:
    - "Gemfile"
    - "*.lock"
    - "*.md"
    - "*.yml"
    - ".ruby-version"
    - "*.gemspec"
    - "*.gem"
    - "test.*"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 125
