AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - "Gemfile"
    - "*.lock"
    - "*.md"
    - "*.yml"
    - ".ruby-version"
    - "*.gemspec"
    - "*.gem"
    - "test.*"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
